backend:
  name: github
  repo: adilsonreisart/original-art # Confirme se o nome do seu repositório é este mesmo
  branch: main

media_folder: "assets/images" # Onde as fotos da Shakira e outros serão salvas
public_folder: "/assets/images"

collections:
  - name: "artes"
    label: "Minhas Artes"
    folder: "_artes" # Ele criará uma pasta para organizar seus posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título da Arte", name: "title", widget: "string" }
      - { label: "Data da Postagem", name: "date", widget: "datetime" }
      - { label: "Imagem da Arte", name: "image", widget: "image" }
      - { label: "Descrição/Técnica", name: "description", widget: "text" }
      - { label: "Preço (Link PayPal)", name: "paypal_link", widget: "string" }

  - name: "paginas"
    label: "Páginas"
    files:
      - name: "bio"
        label: "Minha Bio (Sobre)"
        file: "about.html" # O arquivo que ele vai editar quando você mudar a bio
        fields:
          - { label: "Texto da Bio", name: "body", widget: "markdown" }
